//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Sender
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_UserStatus
    {
        public Gen_UserStatus()
        {
            this.Mem_MemberToGroup = new HashSet<Mem_MemberToGroup>();
        }
    
        public short UserStatusId { get; set; }
        public string UserStatus { get; set; }
    
        public virtual ICollection<Mem_MemberToGroup> Mem_MemberToGroup { get; set; }
    }
}
