//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Sender
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mem_Title
    {
        public Mem_Title()
        {
            this.Mem_Details = new HashSet<Mem_Details>();
        }
    
        public short TitleId { get; set; }
        public string TitleDesc { get; set; }
    
        public virtual ICollection<Mem_Details> Mem_Details { get; set; }
    }
}
