//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Sender
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mem_Contacts
    {
        public int ContactID { get; set; }
        public int MemId { get; set; }
        public string PrimaryNo { get; set; }
        public string AltContactNo { get; set; }
        public short NoType { get; set; }
        public string EmailAdd { get; set; }
        public string EmailAdd2 { get; set; }
    
        public virtual Mem_Info Mem_Info { get; set; }
    }
}
