//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Sender
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mem_MemberToGroup
    {
        public Mem_MemberToGroup()
        {
            this.Gen_UserAccs = new HashSet<Gen_UserAccs>();
        }
    
        public int MemGrpId { get; set; }
        public int MemId { get; set; }
        public short GrpId { get; set; }
        public int MFId { get; set; }
        public short UserStatusId { get; set; }
        public int AddedBy { get; set; }
        public System.DateTime AddedOn { get; set; }
        public int UpdateBy { get; set; }
        public System.DateTime UpdateOn { get; set; }
    
        public virtual ICollection<Gen_UserAccs> Gen_UserAccs { get; set; }
        public virtual Gen_UserGroup Gen_UserGroup { get; set; }
        public virtual Gen_UserStatus Gen_UserStatus { get; set; }
        public virtual Mem_Info Mem_Info { get; set; }
    }
}
