//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Sender
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_AttentionItem
    {
        public MH_AttentionItem()
        {
            this.MH_Mem_AttentionReq = new HashSet<MH_Mem_AttentionReq>();
        }
    
        public int AttItemId { get; set; }
        public string AttItem { get; set; }
    
        public virtual ICollection<MH_Mem_AttentionReq> MH_Mem_AttentionReq { get; set; }
    }
}
