//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Sender
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_MedProcedure
    {
        public MH_MedProcedure()
        {
            this.MH_Mem_MedProcedure = new HashSet<MH_Mem_MedProcedure>();
        }
    
        public int MedProcId { get; set; }
        public string MedProc { get; set; }
        public int AddedBy { get; set; }
        public System.DateTime AddedOn { get; set; }
        public int UpdateBy { get; set; }
        public System.DateTime UpdateOn { get; set; }
        public bool IsDel { get; set; }
    
        public virtual ICollection<MH_Mem_MedProcedure> MH_Mem_MedProcedure { get; set; }
    }
}
