//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Sender
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIS_Visit
    {
        public int VisitId { get; set; }
        public int MemId { get; set; }
        public System.DateTime VisitDate { get; set; }
        public string Symptoms { get; set; }
        public string Diagnoses { get; set; }
        public string MedFacility { get; set; }
        public string MedConsultant { get; set; }
        public string VisitTags { get; set; }
        public short VisitStatusId { get; set; }
        public short ReviewStatusId { get; set; }
        public int AddedBy { get; set; }
        public System.DateTime AddedOn { get; set; }
        public int UpdateBy { get; set; }
        public System.DateTime UpdateOn { get; set; }
        public bool IsDel { get; set; }
    
        public virtual Mem_Info Mem_Info { get; set; }
        public virtual VIS_ReviewStatus VIS_ReviewStatus { get; set; }
        public virtual VIS_VisitStatus VIS_VisitStatus { get; set; }
    }
}
