//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Sender
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class Mem_Images
    {
        public int ImgID { get; set; }
        public int MemId { get; set; }
        public string ImgName { get; set; }
        public int ImgStatusId { get; set; }
        public int AddedBy { get; set; }
        public System.DateTime AddedOn { get; set; }
        public int UpdateBy { get; set; }
        public System.DateTime UpdateOn { get; set; }
        public bool isDel { get; set; }
        public virtual Mem_Info Mem_Info { get; set; }
    }
}
