//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Sender
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mem_Info
    {
        public Mem_Info()
        {
            this.Mem_Contacts = new HashSet<Mem_Contacts>();
            this.Mem_Details = new HashSet<Mem_Details>();
            this.Mem_Images = new HashSet<Mem_Images>();
            this.Mem_MemberToGroup = new HashSet<Mem_MemberToGroup>();
            this.MF_Details = new HashSet<MF_Details>();
            this.MH_Mem_AttentionReq = new HashSet<MH_Mem_AttentionReq>();
            this.MH_Mem_BloodGroup = new HashSet<MH_Mem_BloodGroup>();
            this.MH_Mem_FamilyCondition = new HashSet<MH_Mem_FamilyCondition>();
            this.MH_Mem_MedAllergy = new HashSet<MH_Mem_MedAllergy>();
            this.MH_Mem_MedCondition = new HashSet<MH_Mem_MedCondition>();
            this.MH_Mem_MedProcedure = new HashSet<MH_Mem_MedProcedure>();
            this.MH_Mem_RoutineMeds = new HashSet<MH_Mem_RoutineMeds>();
            this.VIS_Visit = new HashSet<VIS_Visit>();
        }
    
        public int MemId { get; set; }
        public short MemTypeId { get; set; }
        public short MemStatusId { get; set; }
        public string ParentMemId { get; set; }
        public System.DateTime AddedOn { get; set; }
        public int AddedBy { get; set; }
        public System.DateTime UpdateOn { get; set; }
        public int UpdateBy { get; set; }
    
        public virtual Gen_MemberType Gen_MemberType { get; set; }
        public virtual ICollection<Mem_Contacts> Mem_Contacts { get; set; }
        public virtual ICollection<Mem_Details> Mem_Details { get; set; }
        public virtual ICollection<Mem_Images> Mem_Images { get; set; }
        public virtual Mem_Status Mem_Status { get; set; }
        public virtual ICollection<Mem_MemberToGroup> Mem_MemberToGroup { get; set; }
        public virtual ICollection<MF_Details> MF_Details { get; set; }
        public virtual ICollection<MH_Mem_AttentionReq> MH_Mem_AttentionReq { get; set; }
        public virtual ICollection<MH_Mem_BloodGroup> MH_Mem_BloodGroup { get; set; }
        public virtual ICollection<MH_Mem_FamilyCondition> MH_Mem_FamilyCondition { get; set; }
        public virtual ICollection<MH_Mem_MedAllergy> MH_Mem_MedAllergy { get; set; }
        public virtual ICollection<MH_Mem_MedCondition> MH_Mem_MedCondition { get; set; }
        public virtual ICollection<MH_Mem_MedProcedure> MH_Mem_MedProcedure { get; set; }
        public virtual ICollection<MH_Mem_RoutineMeds> MH_Mem_RoutineMeds { get; set; }
        public virtual ICollection<VIS_Visit> VIS_Visit { get; set; }
    }
}
