//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Sender
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mem_Info
    {
        public Mem_Info()
        {
            this.Mem_Details = new HashSet<Mem_Details>();
        }
    
        public int MemId { get; set; }
        public short MemTypeId { get; set; }
        public short MemStatusId { get; set; }
        public string ParentMemId { get; set; }
        public System.DateTime AddedOn { get; set; }
        public int AddedBy { get; set; }
        public System.DateTime UpdateOn { get; set; }
        public int UpdateBy { get; set; }
    
        public virtual ICollection<Mem_Details> Mem_Details { get; set; }
    }
}
