//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Sender
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class mrmdbEntities : DbContext
    {
        public mrmdbEntities()
            : base("name=mrmdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gen_MemberType> Gen_MemberType { get; set; }
        public virtual DbSet<Gen_UserAccs> Gen_UserAccs { get; set; }
        public virtual DbSet<Gen_UserGroup> Gen_UserGroup { get; set; }
        public virtual DbSet<Gen_UserStatus> Gen_UserStatus { get; set; }
        public virtual DbSet<Mem_Contacts> Mem_Contacts { get; set; }
        public virtual DbSet<Mem_Details> Mem_Details { get; set; }
        public virtual DbSet<Mem_Info> Mem_Info { get; set; }
        public virtual DbSet<Mem_MemberToGroup> Mem_MemberToGroup { get; set; }
        public virtual DbSet<Mem_Status> Mem_Status { get; set; }
        public virtual DbSet<Mem_Title> Mem_Title { get; set; }
        public virtual DbSet<MF_Details> MF_Details { get; set; }
        public virtual DbSet<MF_Status> MF_Status { get; set; }
    
        public virtual ObjectResult<usp_Gen_UserLogin_Result> usp_Gen_UserLogin(string uname, string passkey)
        {
            var unameParameter = uname != null ?
                new ObjectParameter("uname", uname) :
                new ObjectParameter("uname", typeof(string));
    
            var passkeyParameter = passkey != null ?
                new ObjectParameter("passkey", passkey) :
                new ObjectParameter("passkey", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Gen_UserLogin_Result>("usp_Gen_UserLogin", unameParameter, passkeyParameter);
        }
    }
}
