//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Sender
{
    using System;
    using System.Collections.Generic;
    
    public partial class Msg
    {
        public int id { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
        public string sender { get; set; }
        public string mobile { get; set; }
        public string msg1 { get; set; }
    }
}
